# port
server:
  port: 8761
spring:
  application:
    name: allst-eureka-eureka # 应用名称，应用名称会在Eureka中作为服务名称
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    hostname: localhost  # 当前eureka实例的主机名
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url: # 配置客户端所交互的Eureka Server的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
